### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by imaninyasia** [imaninyasia/project2#1]
@gittheking @jasonseminara @trevorpreston @rapala61 @irwintsay

i'm trying to console.log the body of the json, just to see if it's connecting. but i'm going nowhere with it..

**Comment by gittheking** [comment]
@imaninyasia creating an issue with a short description isn't enough, please adhere to our [seeking help guide](https://git.generalassemb.ly/gist/bobbyking/3b7e8d65205a6a0580559cd304e1ce84) and supply the following:
- What have you done the try and solve it and to what extent has that worked?
- code snippet of the method that is giving you an issue
- Is there an output?
- Is there an error? If there is an error, what error is it?

**Comment by imaninyasia** [comment]
@gittheking @jasonseminara @trevorpreston @rapala61 @irwintsay
i don't know what the exact issue is, the output is undefined, i've tried moving stuff around... i need help... 

function findPets(req, res, next) {

  const API_URL = `http://api.petfinder.com/pet.find?format=json&key=${API_KEY}&location=10001&animal=dog`;

  fetch(`${API_URL}`)
  .then((result) => {
    res.results = results;
    console.log(results);
    next();
  })
  .catch((err) => {
    res.err = err;
    next();
  });
}

**Comment by rapala61** [comment]
Im not sure if this issue is fixed:
try fetch `(`${API_URL}`)` vs `fetch(${API_URL})` You are missing the back ticks.

Also, fetch needs the response to be parsed into JSON:

```
fetch(`${API_URL}`)
    .then((response) => {
        return response.json();
    })
    .then((results) => {
        res.results = results;
        console.log(results);
        next();
    })
    .catch((err) => {
        res.err = err;
        next();
    });
```
